name: tv_monitor
description: "Android TV advertising player with Clean Architecture and BLoC"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  # Dependency Injection
  get_it: ^8.0.2

  # Networking
  dio: ^5.8.0+1
  web_socket_channel: ^2.4.0

  # Local Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Storage & Permissions
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  disk_space_plus: ^0.2.1

  # Device Info
  device_info_plus: ^12.0.0
  package_info_plus: ^8.1.1

  # Video Player
  video_player: ^2.9.2
  chewie: ^1.8.5

  # Screenshot Capture
  screenshot: ^3.0.0

  # Utilities
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.2
  http: ^1.2.2
  dartz: ^0.10.1
  logger: ^2.5.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  mocktail: ^1.0.4
  # Note: bloc_test has version conflict with isar_generator
  # Add it back when needed for testing or use different versions

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/video/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
